### ISSUE TITLE
Can't login to management console

### ISSUE THREAD

**Issue by lint2015** [koush/scrypted#111]
Hi,

I'm having a little trouble getting started with Scrypted. I have it running in a docker container on a Synology NAS. Setting up the container was straightforward, but when I try to open the management console using the secure port, I get a "connection reset" error.

On the insecure port, I'm presented with screen to create a login account as expected. On first access, the logs indicate that it downloads the web UI assets. I'm uncertain whether the stuff logged towards the end of this process are errors or an expected part of the process:

```
installing package @scrypted/core 0.0.174
--
downloaded tarball 6754020
parsing entry package/ui/tslint.json.foo
parsing entry package/ui/public/index.html
parsing entry package/ui/public/favicon.ico
parsing entry package/ui/public/images/cameraloading.jpg
parsing entry package/ui/babel.config.js
parsing entry package/ui/vue.config.js
parsing entry package/ui/public/manifest.json
parsing entry package/client/package-lock.json
parsing entry package/ui/package-lock.json
parsing entry package/client/package.json
parsing entry package/package.json
parsing entry package/ui/package.json
parsing entry package/client/tsconfig.json
parsing entry package/ui/tsconfig.json
parsing entry package/README.md
parsing entry package/ui/README.md
parsing entry package/ui/public/img/icons/apple-touch-icon-152x152.png
parsing entry package/ui/public/img/icons/favicon-128x128.png
parsing entry package/ui/public/img/icons/favicon-144x144.png
parsing entry package/ui/public/img/icons/favicon-152x152.png
parsing entry package/ui/public/img/icons/favicon-16x16.png
parsing entry package/ui/public/img/icons/favicon-192x192.png
parsing entry package/ui/public/img/icons/favicon-32x32.png
parsing entry package/ui/public/img/icons/favicon-384x384.png
parsing entry package/ui/public/img/icons/favicon-512x512.png
parsing entry package/ui/public/img/icons/favicon-72x72.png
parsing entry package/ui/public/img/icons/favicon-96x96.png
parsing entry package/ui/public/img/icons/icon-128x128.png
parsing entry package/ui/public/img/icons/icon-144x144.png
parsing entry package/ui/public/img/icons/icon-152x152.png
parsing entry package/ui/public/img/icons/icon-192x192.png
parsing entry package/ui/public/img/icons/icon-384x384.png
parsing entry package/ui/public/img/icons/icon-512x512.png
parsing entry package/ui/public/img/icons/icon-72x72.png
parsing entry package/ui/public/img/icons/icon-96x96.png
parsing entry package/ui/public/img/icons/msapplication-icon-144x144.png
parsing entry package/ui/public/img/icons/safari-pinned-tab.svg
parsing entry package/client/index.ts
parsing entry package/ui/shims-vue.d.ts
parsing entry package/dist/main.nodejs.js.LICENSE.txt
parsing entry package/ui/public/robots.txt
parsing entry package/dist/plugin.zip
npm package files: package/ui/tslint.json.foo, package/ui/public/index.html, package/ui/public/favicon.ico, package/ui/public/images/cameraloading.jpg, package/ui/babel.config.js, package/ui/vue.config.js, package/ui/public/manifest.json, package/client/package-lock.json, package/ui/package-lock.json, package/client/package.json, package/package.json, package/ui/package.json, package/client/tsconfig.json, package/ui/tsconfig.json, package/README.md, package/ui/README.md, package/ui/public/img/icons/apple-touch-icon-152x152.png, package/ui/public/img/icons/favicon-128x128.png, package/ui/public/img/icons/favicon-144x144.png, package/ui/public/img/icons/favicon-152x152.png, package/ui/public/img/icons/favicon-16x16.png, package/ui/public/img/icons/favicon-192x192.png, package/ui/public/img/icons/favicon-32x32.png, package/ui/public/img/icons/favicon-384x384.png, package/ui/public/img/icons/favicon-512x512.png, package/ui/public/img/icons/favicon-72x72.png, package/ui/public/img/icons/favicon-96x96.png, package/ui/public/img/icons/icon-128x128.png, package/ui/public/img/icons/icon-144x144.png, package/ui/public/img/icons/icon-152x152.png, package/ui/public/img/icons/icon-192x192.png, package/ui/public/img/icons/icon-384x384.png, package/ui/public/img/icons/icon-512x512.png, package/ui/public/img/icons/icon-72x72.png, package/ui/public/img/icons/icon-96x96.png, package/ui/public/img/icons/msapplication-icon-144x144.png, package/ui/public/img/icons/safari-pinned-tab.svg, package/client/index.ts, package/ui/shims-vue.d.ts, package/dist/main.nodejs.js.LICENSE.txt, package/ui/public/robots.txt, package/dist/plugin.zip
i undefined state change: providedInterfaces DeviceProvider,EngineIOHandler,HttpRequestHandler,Readme
i undefined state change: interfaces DeviceProvider,EngineIOHandler,HttpRequestHandler,Readme
i undefined state change: providerId 1
i undefined state change: providedName Scrypted Core
i undefined state change: providedType DeviceProvider
i undefined state change: type DeviceProvider
i undefined state change: name Scrypted Core
a undefined New Device Added.
alert {
timestamp: 1642122509096,
level: 'a',
message: 'New Device Added.',
path: '/device/1',
title: undefined
}
i undefined loading @scrypted/core
i undefined pid 41
loading wrtc failed. trying @koush/wrtc fallback.
 
i undefined state change: providedInterfaces BufferConverter,HttpRequestHandler
i undefined state change: interfaces BufferConverter,HttpRequestHandler
i undefined state change: providerId 1
i undefined state change: providedName HTTP file host
i undefined state change: providedType API
i undefined state change: type API
i undefined state change: name HTTP file host
a undefined New Device Added.
alert {
timestamp: 1642122510717,
level: 'a',
message: 'New Device Added.',
path: '/device/2',
title: undefined
}
invalidating on request
i undefined state change: providedInterfaces OnOff,Settings
i undefined state change: interfaces OnOff,Settings
i undefined state change: providerId 1
i undefined state change: providedName Autoupdate Plugins
i undefined state change: providedType Automation
i undefined state change: type Automation
i undefined state change: name Autoupdate Plugins
a undefined New Device Added.
alert {
timestamp: 1642122510724,
level: 'a',
message: 'New Device Added.',
path: '/device/3',
title: undefined
}
invalidating on request
plugin successfully loaded
 
i undefined loaded @scrypted/core
i undefined state change: providedInterfaces BufferConverter,HttpRequestHandler
i undefined state change: interfaces BufferConverter,HttpRequestHandler
i undefined state change: providerId 1
i undefined state change: providedName HTTPS file host
i undefined state change: providedType API
i undefined state change: type API
i undefined state change: name HTTPS file host
a undefined New Device Added.
alert {
timestamp: 1642122510743,
level: 'a',
message: 'New Device Added.',
path: '/device/4',
title: undefined
}
invalidating on request
i undefined state change: on true
i undefined automation is turned off, and will not be scheduled.
i undefined automation is waiting for event trigger.
i undefined event will fire at Fri Jan 14 2022 03:15:00 GMT+0000 (Coordinated Universal Time)
i undefined state change: fromMimeType */*
i undefined state change: toMimeType text/x-insecure-local-uri
i undefined state change: fromMimeType */*
i undefined state change: toMimeType text/x-local-uri
```

After this I'm taken to the login screen but every login attempt returns me to the login screen with the following appearing in the log:

`rejected request false undefined /endpoint/@scrypted/core/engine.io/api/?EIO=4&transport=polling&t=NvM8GJ4`

(The string after t= is different each time)

Any help would be appreciated. Thanks.

**Comment by lint2015** [comment]
Hi I'm able to connected to the secure port (I left out https:// originally). However since I'm only accessing the management console locally I'd like to use the insecure port, is there any way to resolve my issue with the insecure port? Thanks.

**Comment by koush** [comment]
I'll take a look, but use the secure port. The insecure port is only for devices that cant access invalid ssl certs.

**Comment by koush** [comment]
I think this was fixed, race condition on startup.

**Comment by lint2015** [comment]
Thanks! Got my cameras set up, works much better than homebridge + ffmpeg camera with the added benefit of HKSV added! Just gotta figure out a few remaining issues over the next few days.

**Comment by cheme75** [comment]
@koush finally fumbled my way to get scrypted running in a docker container on my win10 pc using docker-compose. however, i cannot open the UI in either firefox or edge - I've allowed ports 10443 and 11080 on my private network, made sure my hosts file is not blocking anything and I still get nothing - on 3rd reboot all I get is 
Unable to connect. 
Firefox can’t establish a connection to the server at 127.0.0.1:10443.
Trying to connect from another pc on my lan, I get connection timed out trying to connect
A little help pointing me in the right direction would be appreciated. I hear good things about scrypted but this is frustrating.

**Comment by lint2015** [comment]
Did you set up scrypted on Docker inside WSL2? Check if you can access localhost:10443 from within WSL, if you can then you probably haven't set up port forwarding properly on the computer onto WSL.

I'm not too familiar with WSL but you could probably also find the IP address of the WSL virtual machine and type that into your browser instead of 127.0.0.1?

**Comment by cheme75** [comment]
Thanks for some ideas! Been a frustrating day. I’ll have to find some info on wsl2. I just assumed all applications would be at the same ip as the ethernet adapter of the pc, I just thought different apps use different ports. The docker install originally was for a crypto node and setup wsl2. I really never looked at the wsl2 portion since the original container just ran and then the wyze bridge just ran and neither required directly dealing with wsl2. My subnet is the typical 192.168.1.xxx, however I see some router traffic going to 192.168.0.xxx - maybe that’s the wsl2 VM. Anyway, thx for reply.

**Comment by lint2015** [comment]
You're welcome. A virtual machine can either share the same IP address as the host machine or have its own IP address, depending on how it's set up. If it has its own IP address, the VM should be on the same subnet has the host machine, so I'm not sure you're looking in the right place there.

I'd recommend you follow the [Windows installation instructions](https://github.com/koush/scrypted/wiki/Installation:-WSL2-Windows) if you haven't already and join the discord for help on setting it up.

**Comment by cheme75** [comment]
ipconfig is actually showing 2 vethernet adapters at 172.x.x.x - one says it wsl - tried it at browser with port 10443 and 11080. neither worked so probably either gotta change it so sane subnet or figure out how to fwd it or read a lot more on figuring this out. Was hoping I could just follow examples to setup the yml file like the wyze bridge and go from there.

**Comment by cheme75** [comment]
> You're welcome. A virtual machine can either share the same IP address as the host machine or have its own IP address, depending on how it's set up. If it has its own IP address, the VM should be on the same subnet has the host machine, so I'm not sure you're looking in the right place there.
> 
> I'd recommend you follow the [Windows installation instructions](https://github.com/koush/scrypted/wiki/Installation:-WSL2-Windows) if you haven't already and join the discord for help on setting it up.

Looking at ipconfig - shows my eth adapter with ip info on my 192 subnet, also shows virtual adapters - default and wsl with their ip info, neither of which has a gateway ip, and both are assigned to different 172 subnet. 

Guess I’ll delete container and start over. Was hoping avoid yet another social app, will get on discord and take a look.

**Comment by cheme75** [comment]
How do I join the discord?  It says something about an invite or link - don’t see anything here.
