### ISSUE TITLE
Memory leak crashing Proxmox

### ISSUE THREAD

**Issue by GeeEmm88** [koush/scrypted#1921]
- [ x] I checked that my issue isn't already filed: [Search open issues](https://github.com/koush/scrypted/issues).
- [ x] I checked the relevant camera/device and/or plugin `Log` in the `Management Console` for errors or warnings that may help identify and resolve the issue myself.

**Describe the bug**
Every few hours the memory consumption of the (recommended) Proxmox LCX instance of Scrypted increases from on average 2GB to the maximum assigned 16GB (default value). Usually the entire Proxmox mode is crashing afterwards or the node runs into OOM…

**To Reproduce**
Wait few hours and memory consumption increases like shown on screenshots

**Expected behavior**
Memory should stay rather stable and not increase to max killing machine

**Screenshots**
See screenshots

**Logs**
N/A

**Server (please complete the following information):**
-  Default Proxmox LCX instance on Proxmox V9
- Doorbird + FFMPEG plugins for in total 5 cameras

**Hardware Model (please complete the following information):**
Dell Wyse 5070

**Client (please complete the following information, if applicable):**
See screenshot

![Image](https://github.com/user-attachments/assets/3bf54ece-90e4-4a8a-aad5-06159052440f)
![Image](https://github.com/user-attachments/assets/e932898c-16e2-4a1b-a9d6-c6f22d4021c4)
![Image](https://github.com/user-attachments/assets/3063faab-2754-4949-811f-dc4feefb3c2c)
![Image](https://github.com/user-attachments/assets/763bf99b-3463-438e-92aa-fce85131fcef)
![Image](https://github.com/user-attachments/assets/8b30bd70-ef07-4795-8111-22790353f7fd)

**Comment by koush** [comment]
maybe fixed with this:
https://github.com/koush/scrypted/commit/34f0529691e8d6af1dec7a3a3d26ab0e3b1a2cff

**Comment by GeeEmm88** [comment]
![Image](https://github.com/user-attachments/assets/a07e8f77-6e4e-4bf2-972e-ef1b9901ef5f)

@koush Looks way better now after commit [34f0529](https://github.com/koush/scrypted/commit/34f0529691e8d6af1dec7a3a3d26ab0e3b1a2cff) (see red line)

Thank you for your quick support!

**Comment by koush** [comment]
may need to wait longer to determine its fixed so let me know.

**Comment by GeeEmm88** [comment]
@koush I will keep observing it and reach out to you in case issue reoccurs again. So far it still looks good…

![Image](https://github.com/user-attachments/assets/99a308b7-c511-452c-9901-d10ecd59afe3)

**Comment by GeeEmm88** [comment]
Dear @koush , 

Seems like the issue is back again. The memory usage suddenly increased to max and the server crashes requiring reboot.

![Image](https://github.com/user-attachments/assets/8be26d26-2687-4bc5-9d1c-ee9bdcb3eaf2)

**Comment by yukifolf** [comment]
Hi, 
I've got the same problem, I cannot even restart or do anything to lxc container itself other than unplugging server from power.
