### ISSUE TITLE
Memory leak - linear memory consumption

### ISSUE THREAD

**Issue by benchristian88** [koush/scrypted#729]
My install on a proxmox debian lxc seems to have a consistent memory leak. I have 8gb of ram allocated, and on restart it boots at 20%, and slowly climbs to consume all memory, until I restart scrypted.  Image below shows a few restarts to test it’s that and not proxmox.

none of my other vms or lxc seem to have this issue. I can’t see any logs, where would I look? 

Currently 2 cams via ring plugin, and 8 other rtsp .

![IMG_1953](https://user-images.githubusercontent.com/93822871/232274723-e17ee70d-c511-4504-b4b5-8e87c7a7a07b.jpeg)

I can’t tell what version this started, or if I have always had it, as I only recently started monitoring the vital signs of my proxmox servers 

- and thanks for making scrypted!   It’s really cool!

**Comment by koush** [comment]
You use a software motion sensor, and can you check how many running Python processes there are?

**Comment by benchristian88** [comment]
Yes pamdiff.  The 8 camera are wyze using rtsp from the wyze bridge and have that enabled .  2 are ring with the plug-in.

How do I check python processes?

**Comment by phgerin** [comment]
I have the same problem with LXC container, Ubuntu VM, debian or docker in a VM or LXC. All have increasing ram usage until Scrypted crahes.  I have tested on 3 differents server. 

HTOP shows that some process slowly use more and more ram.

**Comment by phgerin** [comment]
Here are 2 htop screenshot at 1 hour interval.

![image](https://user-images.githubusercontent.com/78903348/232307891-2e5ca48f-5f52-4341-bc6f-03446ac20ac2.png)

![image](https://user-images.githubusercontent.com/78903348/232307947-c4459f5c-11bd-4edc-9258-bea0b6b2da48.png)

**Comment by benchristian88** [comment]
Looks like it might be happening in the ha addon too. 

https://www.reddit.com/r/homeassistant/comments/12oanwf/home_assistant_memory_use_is_hitting_100/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

**Comment by koush** [comment]
I think I fixed this with the video analysis update earlier this morning, please verify that the python processes stop leaking.

**Comment by benchristian88** [comment]
Appears to be sitting well now. Think we got it! Thank you! Fast fix legends

**Comment by benchristian88** [comment]
Hi koush,  I may have spoken too early. Seems to be still growing, gone from 20% to 40% memory use on my lxc through today and still climbing.   Will keep an eye on it and see how high. Anything I can check that would help? 

![IMG_1954](https://user-images.githubusercontent.com/93822871/232401407-c7ccb196-efef-4d76-ad46-e6a0219c1b95.jpeg)

**Comment by koush** [comment]
Are there still run away python processes?

**Comment by phgerin** [comment]
Still not fixed for me. 
The process /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/prebuffer-mixin  has still always increasing memory usage.

**Comment by koush** [comment]
> Hi koush, I may have spoken too early. Seems to be still growing, gone from 20% to 40% memory use on my lxc through today and still climbing. Will keep an eye on it and see how high. Anything I can check that would help?

Use htop or something similar to figure out what process is eating the memory.

**Comment by benchristian88** [comment]
hopefully this might help.

`USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       59180  2.3  4.4 3228544 376296 ?      Sl   06:27   4:03 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59310 13.4  2.1 1355576 179208 ?      SLl  06:27  22:45 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59730 13.0  2.0 1384184 169564 ?      SLl  08:15   7:56 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59318 14.2  2.0 1372288 169036 ?      SLl  06:27  24:03 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59164  0.9  2.0 1012144 167980 ?      Sl   06:27   1:39 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59337 11.0  1.9 1372288 165860 ?      SLl  06:27  18:40 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59308 14.0  1.9 1372288 165452 ?      SLl  06:27  23:43 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59323 13.9  1.9 1372288 162976 ?      SLl  06:27  23:34 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59863 14.6  1.9 1378452 162200 ?      SLl  08:44   4:40 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59320 14.2  1.9 1378364 161156 ?      SLl  06:27  24:03 /usr/bin/python3 -c from multiprocessing.spawn imp
root          46  0.0  1.7 249276 148780 ?       Ss   Apr15   2:11 /lib/systemd/systemd-journald
root       59146  0.1  1.7 1054808 145472 ?      Sl   06:27   0:10 node /root/.scrypted/node_modules/.bin/scrypted-se
root       59179 12.5  1.2 945396 106840 ?       Sl   06:27  21:17 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59194  0.1  1.2 964216 105044 ?       Sl   06:27   0:14 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59211  0.0  1.1 1025380 95952 ?       Sl   06:27   0:03 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59193  7.3  0.8 971620 71788 ?        Sl   06:27  12:24 python3 -u /root/.scrypted/node_modules/@scrypted/
root       59176  0.1  0.8 465824 70464 ?        Sl   06:27   0:10 python3 -u /root/.scrypted/node_modules/@scrypted/
root         135  0.0  0.7 910624 67092 ?        Ssl  Apr15   0:00 npm exec scrypted serve
root       59157  0.0  0.7 840184 59952 ?        Sl   06:27   0:01 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59170  1.2  0.6 897380 57440 ?        Sl   06:27   2:03 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59133  0.0  0.6 709220 56644 ?        Sl   06:27   0:00 npm exec scrypted-serve
root       59204  0.0  0.6 765372 53056 ?        Sl   06:27   0:01 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59196  0.0  0.6 894496 51540 ?        Sl   06:27   0:01 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root         322  0.0  0.5 594692 43164 ?        Sl   Apr15   0:00 node /root/.npm/_npx/f8ff587849d254b8/node_modules
root         137  0.0  0.2 109060 21120 ?        Ssl  Apr15   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/un
root       11893  0.0  0.2 286604 18696 ?        Ssl  Apr15   0:00 /usr/libexec/packagekitd
root       60361  0.2  0.1  89876 15612 ?        S    09:15   0:00 /root/.scrypted/node_modules/ffmpeg-static/ffmpeg 
systemd+      93  0.0  0.1  24116 11976 ?        Ss   Apr15   0:01 /lib/systemd/systemd-resolved
root       59281  0.0  0.1  17676 10952 ?        S    06:27   0:00 /usr/bin/python3 -c from multiprocessing.resource_
root           1  0.0  0.1 165528 10028 ?        Ss   Apr15   0:01 /sbin/init
systemd+      64  0.0  0.0  16056  6984 ?        Ss   Apr15   0:01 /lib/systemd/systemd-networkd
root       11897  0.0  0.0 233504  6976 ?        Ssl  Apr15   0:00 /usr/libexec/polkitd --no-debug
postfix      315  0.0  0.0  40352  6672 ?        S    Apr15   0:00 qmgr -l -t unix -u
postfix    59854  0.0  0.0  40304  6592 ?        S    08:39   0:00 pickup -l -t unix -u -c
root          99  0.0  0.0  13492  6544 ?        Ss   Apr15   0:00 /lib/systemd/systemd-logind
root          82  0.0  0.0  99892  5932 ?        Ssl  Apr15   0:00 /sbin/dhclient -4 -v -i -pf /run/dhclient.eth0.pid
root         313  0.0  0.0  40052  5000 ?        Ss   Apr15   0:00 /usr/lib/postfix/sbin/master -w
message+      96  0.0  0.0   8256  4668 ?        Ss   Apr15   0:00 /usr/bin/dbus-daemon --system --address=systemd: -
root          98  0.0  0.0 151164  4628 ?        Ssl  Apr15   0:40 /usr/sbin/rsyslogd -n -iNONE
root         139  0.0  0.0   7168  4428 pts/1    Ss   Apr15   0:00 /bin/login -f
root         318  0.0  0.0   4924  4120 pts/1    S    Apr15   0:00 -bash
root       60366  0.0  0.0   6904  2968 pts/1    R+   09:17   0:00 ps aux --sort -%mem
root          95  0.0  0.0   3748  2460 ?        Ss   Apr15   0:00 /usr/sbin/cron -f
root         138  0.0  0.0   2508  1772 pts/0    Ss+  Apr15   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud con
root         140  0.0  0.0   2508  1728 pts/2    Ss+  Apr15   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud tty
root         321  0.0  0.0   2484   512 ?        S    Apr15   0:00 sh -c -- scrypted serve
root       59145  0.0  0.0   2484   508 ?        S    06:27   0:00 sh -c -- scrypted-serve`

**Comment by koush** [comment]
that text is cut off. please get a full copy of the terminal.

**Comment by benchristian88** [comment]
try this

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       59180  2.4  4.7 3233592 397120 ?      Sl   06:27  17:37 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root          46  0.0  2.5 331020 213964 ?       Ss   Apr15   2:22 /lib/systemd/systemd-journald
root       59146  0.1  2.3 1089176 193164 ?      Sl   06:27   0:58 node /root/.scrypted/node_modules/.bin/scrypted-se
root       62324 12.6  2.1 1355320 182556 ?      SLl  12:21  47:57 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59164  1.0  2.1 1019548 180204 ?      Sl   06:27   7:56 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59310  3.8  2.1 1281812 179920 ?      SLl  06:27  28:14 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59730  2.6  2.1 1300040 177156 ?      SLl  08:15  16:18 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59323 14.0  2.0 1372288 169048 ?      SLl  06:27 102:43 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59318 14.2  2.0 1372288 169036 ?      SLl  06:27 104:20 /usr/bin/python3 -c from multiprocessing.spawn imp
root       65845 14.4  2.0 1378364 168700 ?      SLl  16:34  18:09 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59320 14.2  1.9 1378364 167228 ?      SLl  06:27 104:31 /usr/bin/python3 -c from multiprocessing.spawn imp
root       61303  3.6  1.9 1293964 166832 ?      SLl  10:44  17:20 /usr/bin/python3 -c from multiprocessing.spawn imp
root       62523  4.7  1.9 1293964 166584 ?      SLl  12:44  16:46 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59863  2.9  1.9 1293964 166120 ?      SLl  08:44  17:26 /usr/bin/python3 -c from multiprocessing.spawn imp
root       66948 13.2  1.9 1378480 165932 ?      SLl  17:36   8:28 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59308 14.0  1.9 1372288 165452 ?      SLl  06:27 102:43 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59337  8.9  1.9 1287888 163928 ?      SLl  06:27  65:33 /usr/bin/python3 -c from multiprocessing.spawn imp
root       63336 10.3  1.9 1359500 163372 ?      SLl  13:44  30:38 /usr/bin/python3 -c from multiprocessing.spawn imp
root       68035 11.2  1.9 1451840 159812 ?      SLl  18:16   2:41 /usr/bin/python3 -c from multiprocessing.spawn imp
root       65347  9.2  1.8 1293964 158124 ?      SLl  16:17  13:13 /usr/bin/python3 -c from multiprocessing.spawn imp
root       61092  3.0  1.8 1293708 151004 ?      SLl  10:20  15:22 /usr/bin/python3 -c from multiprocessing.spawn imp
root       59179 12.8  1.3 954388 115504 ?       Sl   06:27  93:52 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59194  0.1  1.2 964736 107188 ?       Sl   06:27   0:52 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59211  0.0  1.1 1025892 99452 ?       Sl   06:27   0:10 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59193  7.4  0.9 1635720 78132 ?       Sl   06:27  54:31 python3 -u /root/.scrypted/node_modules/@scrypted/
root       59176  0.1  0.8 465824 70464 ?        Sl   06:27   0:46 python3 -u /root/.scrypted/node_modules/@scrypted/
root         135  0.0  0.7 910624 67092 ?        Ssl  Apr15   0:00 npm exec scrypted serve
root       59204  0.0  0.7 904220 64132 ?        Sl   06:27   0:13 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59157  0.0  0.7 840184 61584 ?        Sl   06:27   0:04 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59133  0.0  0.6 709220 56644 ?        Sl   06:27   0:00 npm exec scrypted-serve
root       59170  1.1  0.6 897796 56424 ?        Sl   06:27   8:46 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root       59196  0.0  0.6 894496 52652 ?        Sl   06:27   0:04 /usr/bin/node /root/.scrypted/node_modules/@scrypt
root         322  0.0  0.5 594692 43164 ?        Sl   Apr15   0:00 node /root/.npm/_npx/f8ff587849d254b8/node_modules
root         137  0.0  0.2 109060 21120 ?        Ssl  Apr15   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/un
root       11893  0.0  0.2 286604 18696 ?        Ssl  Apr15   0:00 /usr/libexec/packagekitd
root       68390  0.2  0.1  90312 15868 ?        S    18:39   0:00 /root/.scrypted/node_modules/ffmpeg-static/ffmpeg 
root       68401  0.6  0.1  89728 15660 ?        S    18:40   0:00 /root/.scrypted/node_modules/ffmpeg-static/ffmpeg 
root       68410  0.0  0.1  89648 15576 ?        S    18:40   0:00 /root/.scrypted/node_modules/ffmpeg-static/ffmpeg 
root       68406  5.0  0.1  89632 15564 ?        S    18:40   0:00 /root/.scrypted/node_modules/ffmpeg-static/ffmpeg 
systemd+      93  0.0  0.1  24116 11976 ?        Ss   Apr15   0:01 /lib/systemd/systemd-resolved
root       59281  0.0  0.1  17676 10952 ?        S    06:27   0:00 /usr/bin/python3 -c from multiprocessing.resource_
root           1  0.0  0.1 165528 10032 ?        Ss   Apr15   0:01 /sbin/init
systemd+      64  0.0  0.0  16056  6984 ?        Ss   Apr15   0:01 /lib/systemd/systemd-networkd
root       11897  0.0  0.0 233504  6976 ?        Ssl  Apr15   0:00 /usr/libexec/polkitd --no-debug
postfix    68405  0.0  0.0  40304  6676 ?        S    18:40   0:00 pickup -l -t unix -u -c
postfix      315  0.0  0.0  40352  6672 ?        S    Apr15   0:00 qmgr -l -t unix -u
root          99  0.0  0.0  13492  6544 ?        Ss   Apr15   0:00 /lib/systemd/systemd-logind
root          82  0.0  0.0  99892  5932 ?        Ssl  Apr15   0:00 /sbin/dhclient -4 -v -i -pf /run/dhclient.eth0.pid
root         313  0.0  0.0  40052  5000 ?        Ss   Apr15   0:00 /usr/lib/postfix/sbin/master -w
message+      96  0.0  0.0   8256  4668 ?        Ss   Apr15   0:00 /usr/bin/dbus-daemon --system --address=systemd: -
root          98  0.0  0.0 151164  4628 ?        Ssl  Apr15   0:42 /usr/sbin/rsyslogd -n -iNONE
root         139  0.0  0.0   7168  4428 pts/1    Ss   Apr15   0:00 /bin/login -f
root         318  0.0  0.0   4924  4120 pts/1    S    Apr15   0:00 -bash
root       68412  0.0  0.0   6904  2992 pts/1    R+   18:40   0:00 ps aux --sort -%mem
root          95  0.0  0.0   3748  2460 ?        Ss   Apr15   0:00 /usr/sbin/cron -f
root         138  0.0  0.0   2508  1772 pts/0    Ss+  Apr15   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud con
root         140  0.0  0.0   2508  1728 pts/2    Ss+  Apr15   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud tty
root         321  0.0  0.0   2484   512 ?        S    Apr15   0:00 sh -c -- scrypted serve
root       59145  0.0  0.0   2484   508 ?        S    06:27   0:00 sh -c -- scrypted-serve

**Comment by koush** [comment]
Ok once it gets to 80% or something, get a process list with the full command arguments visible, as well as memory used. 

Again, look at your what you've pasted, the command arguments are cut off, and I don't have the information I need.

**Comment by benchristian88** [comment]
sorry, i am not that familiar with linux, but worked it out now how to get the full command arguments.  I will do as you asked. thanks.

**Comment by benchristian88** [comment]
`top - 20:54:38 up 5 days, 12:37,  1 user,  load average: 2.90, 1.90, 1.65
Tasks:  82 total,   1 running,  81 sleeping,   0 stopped,   0 zombie
%Cpu(s): 30.2 us,  1.3 sy,  0.0 ni, 68.3 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   8192.0 total,   1499.3 free,   5963.1 used,    729.6 buff/cache
MiB Swap:    512.0 total,    512.0 free,      0.0 used.   2228.9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                    
 108532 root      20   0 1355848 183060  62120 S  20.9   2.2  32:01.51 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=148) --multiprocessing-fork        
 101940 root      20   0 1446292 168744  57884 S  14.0   2.0 156:31.81 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=122) --multiprocessing-fork        
 106507 root      20   0 1384712 174596  61748 S  14.0   2.1  64:38.77 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=133) --multiprocessing-fork        
 109680 root      20   0 1384712 166012  61788 S  13.6   2.0  12:59.77 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=147) --multiprocessing-fork        
  83314 root      20   0  981484 134512  34060 S  13.3   1.6 413:36.15 /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/pam-diff                                 
 110077 root      20   0 1378636 166272  62024 S  13.3   2.0   8:18.25 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=151) --multiprocessing-fork        
 103994 root      20   0 1378636 170972  58068 S  13.0   2.0 140:10.91 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=120) --multiprocessing-fork        
 103828 root      20   0 1372964 162272  57964 S  10.6   1.9 112:02.08 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=107) --multiprocessing-fork        
 103926 root      20   0 1355880 186408  58336 S   4.7   2.2 136:10.07 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=116) --multiprocessing-fork        
 101911 root      20   0 3100048 403228  34392 S   2.0   4.8  28:08.55 /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/prebuffer-mixin                          
  83305 root      20   0  901456  63684  33784 S   0.7   0.8  37:37.10 /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/objectdetector                           
  83311 root      20   0  466080  70224  36320 S   0.7   0.8   3:15.41 python3 -u /root/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py @scrypted/opencv                                          
  83426 root      20   0 1353696 161296  58224 S   0.7   1.9  15:48.80 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=28) --multiprocessing-fork         
  88088 root      20   0 1353696 167496  58736 S   0.7   2.0  20:15.67 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=39) --multiprocessing-fork         
  95071 root      20   0 1294236 160592  58760 S   0.7   1.9  31:35.57 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=101) --multiprocessing-fork        
  83328 root      20   0 2576824  61704  30780 S   0.3   0.7   8:08.47 python3 -u /root/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py @scrypted/python-codecs                                   
  83415 root      20   0 1347620 171772  58332 S   0.3   2.0  19:06.61 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=18) --multiprocessing-fork         
  83442 root      20   0 1288160 156868  58400 S   0.3   1.9  22:39.58 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=37) --multiprocessing-fork         
  86357 root      20   0 1294236 154796  58484 S   0.3   1.8  20:46.68 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=58) --multiprocessing-fork         
  86546 root      20   0 1294268 169664  58416 S   0.3   2.0  20:19.69 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=61) --multiprocessing-fork         
  91474 root      20   0 1294236 169252  58536 S   0.3   2.0  23:15.06 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=90) --multiprocessing-fork         
 106087 root      20   0 1294268 173052  62244 S   0.3   2.1  20:50.40 /usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=16, pipe_handle=135) --multiprocessing-fork        
      1 root      20   0  165528  10060   7732 S   0.0   0.1   0:02.58 /sbin/init                                                                                                                                 
     46 root      20   0  414200 239656 238748 S   0.0   2.9   6:23.57 /lib/systemd/systemd-journald                                                                                                              
     64 systemd+  20   0   16056   6984   6132 S   0.0   0.1   0:03.10 /lib/systemd/systemd-networkd                                                                                                              
     82 root      20   0   99892   5892   4532 S   0.0   0.1   0:00.01 /sbin/dhclient -4 -v -i -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0  
     93 systemd+  20   0   24116  11872   7940 S   0.0   0.1   0:03.52 /lib/systemd/systemd-resolved                                                                                                              
     95 root      20   0    3748   2416   2172 S   0.0   0.0   0:00.35 /usr/sbin/cron -f                                                                                                                          
     96 message+  20   0    8256   4400   3748 S   0.0   0.1   0:00.04 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only                                   
     98 root      20   0  151164   4320   2988 S   0.0   0.1   2:00.17 /usr/sbin/rsyslogd -n -iNONE                                                                                                               
     99 root      20   0   13492   6544   5776 S   0.0   0.1   0:00.43 /lib/systemd/systemd-logind                                                                                                                
    135 root      20   0  910624  67016  35684 S   0.0   0.8   0:00.60 npm exec scrypted serve                                                                                                                    
    137 root      20   0  109060  21072  12664 S   0.0   0.3   0:00.06 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal                                              
    138 root      20   0    2508   1724   1612 S   0.0   0.0   0:00.00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux                                                             
    139 root      20   0    7168   4212   3564 S   0.0   0.1   0:00.00 /bin/login -f                                                                                                                              
    140 root      20   0    2508   1680   1568 S   0.0   0.0   0:00.00 /sbin/agetty -o -p -- \u --noclear --keep-baud tty2 115200,38400,9600 linux                                                                
    313 root      20   0   40052   4952   4304 S   0.0   0.1   0:00.93 /usr/lib/postfix/sbin/master -w                                                                                                            
    315 postfix   20   0   40352   6408   5748 S   0.0   0.1   0:00.21 qmgr -l -t unix -u                                                                                                                         
    318 root      20   0    4924   3464   2188 S   0.0   0.0   0:00.02 -bash                                                                                                                                      
    321 root      20   0    2484    512    444 S   0.0   0.0   0:00.00 sh -c -- scrypted serve                                                                                                                    
    322 root      20   0  594692  43364  31540 S   0.0   0.5   0:00.14 node /root/.npm/_npx/f8ff587849d254b8/node_modules/.bin/scrypted serve                                                                     
  11893 root      20   0  286604  18524  15916 S   0.0   0.2   0:01.22 /usr/libexec/packagekitd                                                                                                                   
  11897 root      20   0  233504   6904   6200 S   0.0   0.1   0:00.00 /usr/libexec/polkitd --no-debug                                                                                                            
  83269 root      20   0  708932  55640  35020 S   0.0   0.7   0:00.31 npm exec scrypted-serve                                                                                                                    
  83280 root      20   0    2484    508    444 S   0.0   0.0   0:00.00 sh -c -- scrypted-serve                                                                                                                    
  83281 root      20   0 1316472 423580  56192 S   0.0   5.0   7:53.48 node /root/.scrypted/node_modules/.bin/scrypted-serve                                                                                      
  83292 root      20   0  840484  62856  39052 S   0.0   0.7   0:16.15 /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/core                                     
  83299 root      20   0 1009612 184724  34576 S   0.0   2.2  43:27.20 /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/homekit                                  
  83329 root      20   0  971812 119320  35680 S   0.0   1.4   3:42.68 /usr/bin/node /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js child @scrypted/ring  `

**Comment by koush** [comment]
might be fixed with python codecs update, let me know

**Comment by kklem0** [comment]
Hmm it's funny, it happened to me today that python-codecs used up my memory, and after I restarted scrypted the problem went away and no longer using much ram.

**Comment by dreondre** [comment]
Facing the same, with 2 Wyze cameras (RTSP) on docker with v0.39. Let me know if I can add any info.
